### ISSUE TITLE
building failure with java 8

### ISSUE THREAD

**Issue by efferre79** [hharrison/java3d-core#22]
I get this errors when trying to compile using 

$ java -version
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)

gen:
    [mkdir] Created dir: /var/tmp/portage/dev-java/j3d-core-1.6.0/work/java3d-core-1.6.0/build/gen
     [copy] Copying 2 files to /var/tmp/portage/dev-java/j3d-core-1.6.0/work/java3d-core-1.6.0/build/classes/javax
     [copy] Copying 5 files to /var/tmp/portage/dev-java/j3d-core-1.6.0/work/java3d-core-1.6.0/build/classes/com
     [copy] Copying 1 file to /var/tmp/portage/dev-java/j3d-core-1.6.0/work/java3d-core-1.6.0/build/gen/src/javax/media/j3d

compile:
    [javac] Compiling 755 source files to /var/tmp/portage/dev-java/j3d-core-1.6.0/work/java3d-core-1.6.0/build/classes
    [javac] Annotation processing got disabled, since it requires a 1.6 compliant JVM
    [javac] ----------
    [javac] 1. ERROR in /var/tmp/portage/dev-java/j3d-core-1.6.0/work/java3d-core-1.6.0/src/javax/media/j3d/J3dQueryProps.java (at line 97)
    [javac]     private class EntrySet extends AbstractSet {
    [javac]                   ^^^^^^^^
    [javac] Duplicate methods named spliterator with the parameters () and () are inherited from the types Set and Collection
    [javac] ----------
    [javac] 2. ERROR in /var/tmp/portage/dev-java/j3d-core-1.6.0/work/java3d-core-1.6.0/src/javax/media/j3d/J3dQueryProps.java (at line 97)
    [javac]     private class EntrySet extends AbstractSet {
    [javac]                   ^^^^^^^^
    [javac] Duplicate methods named spliterator with the parameters () and () are inherited from the types Collection and Iterable
    [javac] ----------
    [javac] ----------
    [javac] 3. ERROR in /var/tmp/portage/dev-java/j3d-core-1.6.0/work/j3d-utils/src/com/sun/j3d/utils/universe/ConfigContainer.java (at line 1503)
    [javac]     private static class ReadOnlySet extends AbstractSet {
    [javac]                          ^^^^^^^^^^^
    [javac] Duplicate methods named spliterator with the parameters () and () are inherited from the types Set and Collection
    [javac] ----------
    [javac] 4. ERROR in /var/tmp/portage/dev-java/j3d-core-1.6.0/work/j3d-utils/src/com/sun/j3d/utils/universe/ConfigContainer.java (at line 1503)
    [javac]     private static class ReadOnlySet extends AbstractSet {
    [javac]                          ^^^^^^^^^^^
    [javac] Duplicate methods named spliterator with the parameters () and () are inherited from the types Collection and Iterable
    [javac] ----------
    [javac] 4 problems (4 errors)

**Comment by philjord** [comment]
My environment compiles happily against 1.8, so I can't reproduce this issue.

So google searching strongly suggests this is an environmet setup issue
https://stackoverflow.com/questions/26480213/java-8-spliterator-iterator-collection-and-default-implemenations-in-interf
and
https://bugs.eclipse.org/bugs/show_bug.cgi?id=409473

Can you run javac -version as the version of that file is what will make the difference.

Sorry I can't be of more help
Phil.

**Comment by efferre79** [comment]
Upgrading to ecj-4.5 solved the issue as indicated in the eclipse bug you cite, closing this issue as solved. Thanks!
