### ISSUE TITLE
Java 11 Compatibility check: java3d-core

### ISSUE THREAD

**Issue by KryniuPL** [hharrison/java3d-core#25]
Hi,
In our system we are using old version of library j3dcore(version 1.5) and we are reaching out to you to check Java 11 compatibility of yours library: java3d-core.

Could you help us by answering the following questions:
1. Can your library replace the old library j3dcore founded by Sun Microsystems.

If yes please give us information about your library: java3d-core.
1. Library Name: <library name.="" e.g:="" activation="">
2. Latest version: <latest 1.1.1="" eg:="" version.="">
3. Latest version Is the library compatible with Java 11 Compatible? (Y/N)
4. Is the library supported with Java 11? (Y/N)
5. (If “N” in compatibility or support) What is the versions that would be compatible and Supported?
6. Date of support availability?</latest></library>

Appreciate your response by 06.09.2018.

Thanks,
Krzysztof Dragan,
PTC Inc. Contractor

**Comment by philjord** [comment]
Yes [ java3d-core 1.6.0](https://github.com/hharrison/java3d-core/releases/tag/1.6.0) can replace the Sun 1.5 version

1 Java3D 1.6.0 has 3 libraries similar to 1.5
 java3d-core
 java3d-utils
 vecmath
2 They are all version1.6.0-final
3 It is compatible with Java 10 when installed with jogl-all-2.3.2, Java 11 has not yet been tested
41.6.0 is a final release so incompatibilities with Java 11 are unlikely to be fixed. The next newest version of Java 3D is [Java3D version 1.7](https://github.com/philjord/java3d-core), which is in a separate repository, it is mavenised for building, but does not publish a pre-built library. Java3D 1.7 has changed the root package names so it is not a drop in replacement of Java3D 1.5
5 Java 10
6 Java 11 support for Java3D 1.7 is expected some time after the formal release of Java11 open JDK.

Hope this is of some help, please feel free to ask further questions,
Phil.

**Comment by prashantraut1802** [comment]
Hi,

When the Java3D 1.7 which will be compatible with java 11 is schedule to release.

Thanks,
Prashant R.
PTC Inc.

**Comment by philjord** [comment]
Basically once a few people have used 1.7 and the feedback is such that it's working ok in a variety of environments, then I'll release it as 1.7.0-final and start on 1.7.1 with some new features.
This may take some time as none of the major projects using Java3D are on Java3D 1.7, but that's ok there's no major rush.
