### ISSUE TITLE
license clarification

### ISSUE THREAD

**Issue by mdolling-gfz** [hharrison/java3d-core#30]
The file [GeometryService.java](https://github.com/hharrison/java3d-core/blob/master/src/javax/media/j3d/GeometryService.java) is missing a license header to put it under the classpath exception of the license.

Without the exception in the header the file basically belongs to a GPL-2.0.

Is this intended or was it just forgotten?

@cxplonka and I need this information for a release.

**Comment by philjord** [comment]
You are correct; as it stands it derives from GPL2 and therefore is GPL2, however this is simply an oversight during commit, everything in the javax.medi.j3d package should have the classpath exception.
@ctrueden can you confirm that we should put the standard license into this file?
@hharrison can you make the change once ctrueden has confirmed?
I'll make a the change in the 1.7 version

**Comment by philjord** [comment]
Can I suggest this as the license header:

/*
 * Copyright (c) 2020 JogAmp Community. All rights reserved.
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
 *
 * This code is free software; you can redistribute it and/or modify it
 * under the terms of the GNU General Public License version 2 only, as
 * published by the Free Software Foundation. The JogAmp Community designates 
 * this particular file as subject to the "Classpath" exception as provided
 * by Sun in the LICENSE file that accompanied this code.
 *
 * This code is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
 * version 2 for more details (a copy is included in the LICENSE file that
 * accompanied this code).
 *
 * The views and conclusions contained in the software and documentation are those
 * of the authors and should not be interpreted as representing official policies,
 * either expressed or implied, of the JogAmp Community.
 *
 */

**Comment by ctrueden** [comment]
I hereby disclaim all copyright interest in my past and future contributions to all Java-3D-related repositories, including hharrison/java3d-core, hharrison/java3d-utils, hharrison/vecmath, philjord/java3d-core, philjord/java3d-utils, philjord/vecmath, scijava/java3d-core, scijava/java3d-utils, and scijava/vecmath. I fully support the licensing of any and all code I produced under whatever license the main copyright holders feel is most appropriate.

**Comment by philjord** [comment]
Thank you Curtis, that's great.

**Comment by hharrison** [comment]
I pushed out an update to my j3d-core repo adding the missing license, it generally matches the form of the rest of the files in the j3d-core repo. Not intending to tag a release, just a reference for anyone that needs clarity on the license.
