### ISSUE TITLE
Support OpenGL ES 1.0 or 2.0 hardware

### ISSUE THREAD

**Issue by xranby** [hharrison/java3d-core#8]
X11 ARM Linux GPU only support OpenGL ES 1 and ES 2

Please design Java3D to use the GL2ES2 or GL2ES1 profile to stay compatible with both desktop and mobile GPU hardware.

**Comment by philjord** [comment]
Java3d 1.7.0 is aimed at providing a gl2es2 profile pipeline, it is underway here https://github.com/philjord/java3d-core under branch dev1.7.0

**Comment by AlessandroBorges** [comment]
I have a serious interest in this subject. I'm Aces, the guy who did the official J3D port to D3D 9.0. Let me know if I can help you.

**Comment by philjord** [comment]
Excellent stuff, I just checked in the last big change to get multiple light structures flowing through to the shaders.
Basically testing is what is needs now.
If you clone these repos and switch to dev1.7.0 you'll find lots of interesting stuff in the java3d-examples project

https://github.com/philjord/java3d-core
https://github.com/philjord/java3d-utils
https://github.com/philjord/vecmath
https://github.com/philjord/java3d-examples


But note this version of Java3D is still locked to awt, so it won't run on Android. 

However that is a project I've already done, and will try to get across to the main code line at some point, but it's complex...

**Comment by AlessandroBorges** [comment]
One of my [projects](https://github.com/AlessandroBorges/madri-gles/tree/master/Canvas/src) brings the android.opengl API to desktop. I guess it may helps development targeting  android, without using Android emulators, etc.
This project includes a [GLSurfaceView](https://github.com/AlessandroBorges/madri-gles/blob/master/Canvas/src/android/opengl/GLSurfaceView.java) able to run a java.awt.Canvas - at desktop side.
